theme: jekyll-theme-merlot
title: M.F. Abdur Rahman & A. Shajitha Nikkah Invitation
description: You are cordially invited to witness our Nikah on Sunday, 20 September 2026.
show_downloads: false
google_analytics:
